# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Initialize
      run: |
        sudo apt-get update
        sudo apt-get install -y vim
        sudo apt-get install -y git
    - name: Clone repositories
      run: |
        # Test framework
        git clone --depth 1  --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis
        # Repository under test
        git clone --depth 1 --branch master --single-branch https://github.com/softoika/fizzbuzz.vim /tmp/fizzbuzz.vim
    - name: Run tests
      run: /tmp/vim-themis/bin/themis
      working-directory: /tmp/fizzbuzz.vim
