# This is a basic workflow to help you get started with Actions

name: windows_vim

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [windows-latest]
        name: [vim-v82-x64]
        include:
          - name: vim-v82-x64
            os: windows-latest
            vim_version: 8.2.0472
            vim_arch: x64
            vim_ver_patch: vim82

    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Download vim
      shell: powershell
      run: Invoke-WebRequest -Uri https://github.com/vim/vim-win32-installer/releases/download/v${{matrix.vim_version}}/gvim_${{matrix.vim_version}}_${{matrix.vim_arch}}.zip -OutFile vim.zip
    - name: Extract vim
      shell: powershell
      run: Expand-Archive -Path vim.zip -DestinationPath $env:USERPROFILE
    - name: Download test runner
      shell: powershell
      run: git clone --depth 1 --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis $env:USERPROFILE\themis
    - name: Run tests
      shell: cmd
      run: |
        SET PATH=%USERPROFILE%\vim\${{matrix.vim_ver_path}};%PATH%;
        SET PATH=%USERPROFILE%\themis\bin;%PATH%;
        vim --version
        themis --reporter spec
